import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'

import styles from '../styles/Home.module.css'
import loginStyles from '../styles/login.module.css'

const KAKAO_JS_KEY = process.env.NEXT_PUBLIC_KAKAO_JS_KEY
const KAKAO_LOGIN_REDIRECT_URI = process.env.NEXT_PUBLIC_KAKAO_LOGIN_REDIRECT_URI

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      {/* next/script 는 next/head 바깥에 위치 해야 한다. */}
      <Script
        src="https://developers.kakao.com/sdk/js/kakao.min.js"
        strategy="lazyOnload"
        onLoad={() => {
          // 카카오 sdk 초기설정
          Kakao.init(KAKAO_JS_KEY);
          console.log(Kakao.isInitialized())
        }}

      />

      <main className={styles.main}>
        <Image className={loginStyles.kakao_login}
               src="/kakao_login/ko/kakao_login_medium_wide.png"
               alt="Kakao Login"
               width={300}
               height={45}
               onClick={() => {
                 Kakao.Auth.authorize({
                   // 사용자가 동의 처리시 추가작업이 필요한 리다이렉트 경로(서버에서 토큰 발급이나 회원가입 등의 추가작업)
                   redirectUri: KAKAO_LOGIN_REDIRECT_URI,
                   // 서버가 토큰 발급 등의 작업에 성공하면(즉 로그인에 성공하면) 이동하고싶은 클라이언트 페이지
                   state: 'http://localhost:3000'
                 });
               }}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}
