import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import loginStyles from '../styles/login.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href="https://zumoney.herokuapp.com/oauth/kakaoAuthorize?redirect_uri=https://localhost:3030">
          <Image
            className={loginStyles.kakao_login}
            src="/kakao_login/ko/kakao_login_medium_wide.png"
            alt="Kakao Login"
            width={300}
            height={45}
          />
        </a>
        <button
          onClick={() => {
            fetch('https://zumoney.herokuapp.com/oauth/test', {
              credentials: 'include',
            })
          }}
        >
          refresh_token이 설정된 cookie 전송 테스트
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
